from _typeshed import Incomplete
from micropython import const as const

PORTRAIT: int
LANDSCAPE: int
PORTRAIT_UPSIDEDOWN: int
LANDSCAPE_UPSIDEDOWN: int
STARTUP_DECO_NONE: int
STARTUP_DECO_MLOGO: int
STARTUP_DECO_INFO: int
_uart_baud_table: Incomplete

class LCD160CR:
    pwr: Incomplete
    i2c: Incomplete
    spi: Incomplete
    i2c_addr: Incomplete
    buf16: Incomplete
    buf19: Incomplete
    buf: Incomplete
    buf1: Incomplete
    array4: Incomplete
    def __init__(
        self,
        connect: Incomplete | None = None,
        *,
        pwr: Incomplete | None = None,
        i2c: Incomplete | None = None,
        spi: Incomplete | None = None,
        i2c_addr: int = 98,
    ) -> None: ...
    def _send(self, cmd) -> None: ...
    def _fcmd2(self, fmt, a0, a1: int = 0, a2: int = 0) -> None: ...
    def _fcmd2b(self, fmt, a0, a1, a2, a3, a4: int = 0) -> None: ...
    def _waitfor(self, n, buf) -> None: ...
    def oflush(self, n: int = 255) -> None: ...
    def iflush(self) -> None: ...
    @staticmethod
    def rgb(r, g, b): ...
    @staticmethod
    def clip_line(c, w, h): ...
    def set_power(self, on) -> None: ...
    w: Incomplete
    h: Incomplete
    def set_orient(self, orient) -> None: ...
    def set_brightness(self, value) -> None: ...
    def set_i2c_addr(self, addr) -> None: ...
    def set_uart_baudrate(self, baudrate) -> None: ...
    def set_startup_deco(self, value) -> None: ...
    def save_to_flash(self) -> None: ...
    def set_pixel(self, x, y, c) -> None: ...
    def get_pixel(self, x, y): ...
    def get_line(self, x, y, buf) -> None: ...
    def screen_dump(self, buf, x: int = 0, y: int = 0, w: Incomplete | None = None, h: Incomplete | None = None) -> None: ...
    def screen_load(self, buf) -> None: ...
    def set_pos(self, x, y) -> None: ...
    def set_text_color(self, fg, bg) -> None: ...
    def set_font(self, font, scale: int = 0, bold: int = 0, trans: int = 0, scroll: int = 0) -> None: ...
    def write(self, s) -> None: ...
    def set_pen(self, line, fill) -> None: ...
    def erase(self) -> None: ...
    def dot(self, x, y) -> None: ...
    def rect(self, x, y, w, h, cmd: int = 114) -> None: ...
    def rect_outline(self, x, y, w, h) -> None: ...
    def rect_interior(self, x, y, w, h) -> None: ...
    def line(self, x1, y1, x2, y2) -> None: ...
    def dot_no_clip(self, x, y) -> None: ...
    def rect_no_clip(self, x, y, w, h) -> None: ...
    def rect_outline_no_clip(self, x, y, w, h) -> None: ...
    def rect_interior_no_clip(self, x, y, w, h) -> None: ...
    def line_no_clip(self, x1, y1, x2, y2) -> None: ...
    def poly_dot(self, data) -> None: ...
    def poly_line(self, data) -> None: ...
    def touch_config(self, calib: bool = False, save: bool = False, irq: Incomplete | None = None) -> None: ...
    def is_touched(self): ...
    def get_touch(self): ...
    def set_spi_win(self, x, y, w, h) -> None: ...
    def fast_spi(self, flush: bool = True): ...
    def show_framebuf(self, buf) -> None: ...
    def set_scroll(self, on) -> None: ...
    def set_scroll_win(
        self, win, x: int = -1, y: int = 0, w: int = 0, h: int = 0, vec: int = 0, pat: int = 0, fill: int = 2016, color: int = 0
    ) -> None: ...
    def set_scroll_win_param(self, win, param, value) -> None: ...
    def set_scroll_buf(self, s) -> None: ...
    def jpeg_start(self, l) -> None: ...
    def jpeg_data(self, buf) -> None: ...
    def jpeg(self, buf) -> None: ...
    def feed_wdt(self) -> None: ...
    def reset(self) -> None: ...
