"""
Basic "operating system" services.

MicroPython module: https://docs.micropython.org/en/v1.25.0-preview/library/os.html

CPython module: :mod:`python:os` https://docs.python.org/3/library/os.html .

The ``os`` module contains functions for filesystem access and mounting,
terminal redirection and duplication, and the ``uname`` and ``urandom``
functions.
"""

from __future__ import annotations
from _typeshed import Incomplete
from stdlib.os import *

sep: str

def normcase(s): ...
def normpath(s): ...
def abspath(s): ...
def join(*args): ...
def split(path): ...
def dirname(path): ...
def basename(path): ...
def exists(path): ...

lexists = exists

def isdir(path): ...
def isfile(path): ...
def expanduser(s): ...
